### ISSUE TITLE
Request For An Update

### ISSUE THREAD

**Issue by tftankham** [DerekK19/Defender#1]
I was very excited to hear about this project. I just recently started using the Mustang amp and was super frustrated that my Mac is too new to run Fender Fuze. It would be great if you could update this code to work with 11.2.3 (intel Mac still). I tried running it and the build failed. 

It says there is no profile for team DX8B97QV93 matching Defender MacOS Development found.

Any help would be greatly appreciated!

**Comment by DerekK19** [comment]
Thanks for the input.

The build is failing because you are missing a provisioning profile. All Mac and iOS apps must be built with a valid provisioning profile. I have not included a provisioning profile with the project, but such a profile would be personal to me, based on my developer account and would only be for my use. A provision profile is also linked to a developer certificate, and if I shipped my own developer certificate I would almost certainly have my Apple developer status removed.

To build the project yourself, you will need an Apple Developer account and Xcode, if you are trying to build, then I assume you have Xcode, maybe have an Apple Developer account and maybe your own developer certificate. You should create a provisioning profile using the same bundle identifier the app uses - uk.co.gordonknight.Defender - (though if you want to and know how to, you can change the bundle id to match something of your own choosing). Then load that provisioning profile into Xcode and select your provisioning profile rather than mine.
